### ISSUE TITLE
[BUG] does not work 

### ISSUE THREAD

**Issue by istarengwa** [PluginBugs/Issues-ScratchIt#11]
**Describe the bug**
hello, when I use a scratch card, on the latest version of the plugin, when a player or myself right-click to use the card, nothing happens at all in game and it displays a huge error in console

**To Reproduce**
1. Right clic with scratch in hand

**Expected behavior**
```
[11:47:48 ERROR]: Could not pass event PlayerInteractEvent to ScratchIt v1.1.19
java.lang.NoClassDefFoundError: Could not initialize class dev.lone.ScratchIt.main.cv
        at dev.lone.ScratchIt.main.be.B(SourceFile:174) ~[ScratchIt_1.1.19.jar:?]
        at dev.lone.ScratchIt.main.be.<init>(SourceFile:94) ~[ScratchIt_1.1.19.jar:?]
        at dev.lone.ScratchIt.main.bg.<init>(SourceFile:98) ~[ScratchIt_1.1.19.jar:?]
        at dev.lone.ScratchIt.main.aB.a(SourceFile:241) ~[ScratchIt_1.1.19.jar:?]
        at dev.lone.ScratchIt.g.a(SourceFile:36) ~[ScratchIt_1.1.19.jar:?]
        at dev.lone.ScratchIt.a.a(SourceFile:204) ~[ScratchIt_1.1.19.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1628]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1983) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Info (please complete the following information):**
 - Server version: purpur 1.18.2
 - Client version: official 1.18.2
 - Plugin version: 1.1.19

**Comment by istarengwa** [comment]
I don't know if it's possible, but I had to update protocolib with its spigot version for another plugin, could it be from that?

**Comment by istarengwa** [comment]
That's it, I put the version of an old backup of my server, and it works again! So if it's possible to fix the plugin with the new version, that would be wonderful =)

**Comment by LoneDev6** [comment]
Post a full log of when the issue occurred.
