### ISSUE TITLE
After digging, the animation does not come and the map stays in my hand.

### ISSUE THREAD

**Issue by ghost** [PluginBugs/Issues-ScratchIt#23]
After digging, the animation does not come and the map stays in my hand.

 - Server version: 1.19.4
 - Client version: 1.19.4
 - Plugin version: latest

```
[06:13:37 WARN]: Exception in thread "Timer-456" java.lang.NullPointerException: Cannot invoke "dev.lone.ScratchIt.main.bz.h()" because "this.i" is null
[06:13:37 WARN]:        at ScratchIt_1.1.19b.jar//dev.lone.ScratchIt.main.bq.h(SourceFile:35)
[06:13:37 WARN]:        at ScratchIt_1.1.19b.jar//dev.lone.ScratchIt.main.ba.a(SourceFile:72)
[06:13:37 WARN]:        at ScratchIt_1.1.19b.jar//dev.lone.ScratchIt.main.aA.a(SourceFile:41)
[06:13:37 WARN]:        at ScratchIt_1.1.19b.jar//dev.lone.ScratchIt.main.bg.i(SourceFile:253)
[06:13:37 WARN]:        at ScratchIt_1.1.19b.jar//dev.lone.ScratchIt.main.bg.A(SourceFile:199)
[06:13:37 WARN]:        at ScratchIt_1.1.19b.jar//dev.lone.ScratchIt.main.bf.run(SourceFile:167)
[06:13:37 WARN]:        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[06:13:37 WARN]:        at java.base/java.util.TimerThread.run(Timer.java:516)
[06:13:45 WARN]: [ScratchIt] Plugin ScratchIt v1.1.19b generated an exception while executing task 10859502
java.lang.NullPointerException: Cannot invoke "dev.lone.ScratchIt.main.bz.h()" because "this.i" is null
        at dev.lone.ScratchIt.main.bq.h(SourceFile:35) ~[ScratchIt_1.1.19b.jar:?]
        at dev.lone.ScratchIt.main.ba.a(SourceFile:72) ~[ScratchIt_1.1.19b.jar:?]
        at dev.lone.ScratchIt.main.aA.a(SourceFile:41) ~[ScratchIt_1.1.19b.jar:?]
        at dev.lone.ScratchIt.main.bg.i(SourceFile:253) ~[ScratchIt_1.1.19b.jar:?]
        at dev.lone.ScratchIt.main.bg.M(SourceFile:373) ~[ScratchIt_1.1.19b.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by LoneDev6** [comment]
I cannot reproduce the issue in the latest plugin update
