### ISSUE TITLE
[BUG]  I got an error using the command

### ISSUE THREAD

**Issue by Baikele** [PluginBugs/Issues-ScratchIt#4]
**To Reproduce**
I got an error using the command

**Info (please complete the following information):**
catserver 1.12.2

**Additional context**
```
[23:42:06] [Server thread/INFO]: WhiteCola issued server command: /ScratchIt
[23:42:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'scratchit' in plugin ScratchIt v1.1.12
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[CraftServer.class:git-CatServer-1.12.2-a8b73e9]
        at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1650) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:1451) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_321]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_321]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:890) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321]
Caused by: java.lang.NullPointerException
        at dev.lone.ScratchIt.main.aN.onCommand(SourceFile:37) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-a8b73e9]
        ... 15 more
```

```
[23:55:45] [Server thread/INFO]: WhiteCola issued server command: /scratchit get defusing_bomb
[23:55:46] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ScratchIt v1.1.12
org.bukkit.event.EventException: null
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:274) [CraftEventFactory.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:241) [CraftEventFactory.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:237) [CraftEventFactory.class:git-CatServer-1.12.2-a8b73e9]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItem(NetHandlerPlayServer.java:1187) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:32) [mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:9) [mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_321]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_321]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:890) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321]
Caused by: java.lang.ExceptionInInitializerError
        at dev.lone.ScratchIt.main.aA.a(SourceFile:241) ~[?:?]
        at dev.lone.ScratchIt.g.a(SourceFile:36) ~[?:?]
        at dev.lone.ScratchIt.a.a(SourceFile:201) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-a8b73e9]
        ... 18 more
Caused by: com.comphenix.protocol.reflect.FieldAccessException: No field with type int exists in class PacketPlayOutEntityDestroy.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
        at dev.lone.ScratchIt.main.bf.<clinit>(SourceFile:47) ~[?:?]
        at dev.lone.ScratchIt.main.aA.a(SourceFile:241) ~[?:?]
        at dev.lone.ScratchIt.g.a(SourceFile:36) ~[?:?]
        at dev.lone.ScratchIt.a.a(SourceFile:201) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-a8b73e9]
        ... 18 more
```

**Comment by Baikele** [comment]
@LoneDev6

**Comment by LoneDev6** [comment]
Thanks, this will be fixed as soon as possible

**Comment by Baikele** [comment]
> 谢谢，这个会尽快解决

If it can be solved, can you tell me as soon as possible?
I love this plugin,

**Comment by LoneDev6** [comment]
In max 30 minutes :)
Thanks

**Comment by Baikele** [comment]
```
[02:08:57] [Server thread/INFO]: WhiteCola issued server command: /scratchit give
[02:08:59] [Server thread/ERROR]: Exception when WhiteCola attempted to tab complete scratchit give WhiteCola 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/scratchit give WhiteCola ' in plugin ScratchIt v1.1.13
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:144) ~[PluginCommand.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.command.Command.tabComplete(Command.java:88) ~[Command.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:219) ~[SimpleCommandMap.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:171) ~[SimpleCommandMap.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.tabCompleteCommand(CraftServer.java:1674) [CraftServer.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.tabComplete(CraftServer.java:1655) [CraftServer.class:git-CatServer-1.12.2-a8b73e9]
        at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:1111) [MinecraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:2503) [pa.class:?]
        at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) [kz.class:?]
        at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) [kz.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_321]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_321]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:890) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321]
Caused by: java.lang.NullPointerException
        at dev.lone.ScratchIt.main.aO.onTabComplete(SourceFile:306) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:132) ~[PluginCommand.class:git-CatServer-1.12.2-a8b73e9]
        ... 18 more
```
The problem doesn't seem to be fixed

**Comment by Baikele** [comment]
![image](https://user-images.githubusercontent.com/70128689/158444739-27e5823f-a7ce-46cc-9767-9e55d9ed271d.png)

**Comment by LoneDev6** [comment]
I need the full log.

**Comment by turnolos** [comment]
@LoneDev6 just bought this plugin and am having the exact same issue. Please fix this, the plugin is in an unusable state as it stands.

**Comment by LoneDev6** [comment]
1.12.2 is not compatible with ScratchIt, as noted in the plugin page.
There is a list of compatible plugins.

I can try adding compatibility again but Spigot 1.12.2 has some limitations I can't bypass.

**Comment by LoneDev6** [comment]
Added 1.12.2 support! Have fun.
It has a limitation tho: loading time is longer because of a Spigot bug, please don't report this.
