### ISSUE TITLE
[BUG] still can't use

### ISSUE THREAD

**Issue by Baikele** [PluginBugs/Issues-ScratchIt#5]
**To Reproduce**
I gave a default card through Give, and then I right-clicked, couldn't use it and reported an error!

**Info (please complete the following information):**
 - Server version: (catserver 1.12.2)

**Additional context**
```
[02:18:48] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ScratchIt v1.1.13
org.bukkit.event.EventException: null
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:274) [CraftEventFactory.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:241) [CraftEventFactory.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:237) [CraftEventFactory.class:git-CatServer-1.12.2-a8b73e9]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:1187) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) [mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) [mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_321]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_321]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:890) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 4, Size: 4)
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:369) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
        at dev.lone.ScratchIt.main.cv.e(SourceFile:103) ~[?:?]
        at dev.lone.ScratchIt.main.be.y(SourceFile:183) ~[?:?]
        at dev.lone.ScratchIt.main.be.<init>(SourceFile:95) ~[?:?]
        at dev.lone.ScratchIt.main.bg.<init>(SourceFile:96) ~[?:?]
        at dev.lone.ScratchIt.main.aB.a(SourceFile:241) ~[?:?]
        at dev.lone.ScratchIt.g.a(SourceFile:36) ~[?:?]
        at dev.lone.ScratchIt.a.a(SourceFile:201) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-a8b73e9]
        ... 18 more

```

**Comment by LoneDev6** [comment]
I see you're using cat which is an unofficial Spigot fork and you're using the wrong version.
ScratchIt is not supported on 1.12.2 as clearly stated in the plugin page.
![immagine](https://user-images.githubusercontent.com/27242001/158552755-98dd7c59-9e5b-4a09-91e7-dc8ba26de827.png)
![immagine](https://user-images.githubusercontent.com/27242001/158552771-2c62404d-476a-4759-bddd-2419af0e75d6.png)


Let me know and I'll send you a refund without any problem.

**Comment by Baikele** [comment]
> 我看到您使用的是非官方的 Spigot 叉子 cat 并且您使用了错误的版本。 正如插件页面中明确指出的那样，ScratchIt 在 1.12.2 上不受支持。 ![想象](https://user-images.githubusercontent.com/27242001/158552755-98dd7c59-9e5b-4a09-91e7-dc8ba26de827.png) ![想象](https://user-images.githubusercontent.com/27242001/158552771-2c62404d-476a-4759-bddd-2419af0e75d6.png)
> 
> 让我知道，我会毫无问题地给您退款。

No refund is possible, I still hope you can fix the bug!

**Comment by LoneDev6** [comment]
It's not a bug, simply 1.12.2 has limitations which can't let me implement this plugin correctly.
I can refund you without any issue.

**Comment by Baikele** [comment]
> It's not a bug, simply 1.12.2 has limitations which can't let me implement this plugin correctly. I can refund you without any issue.

No need, thanks, great plugin, I will support it, but I need to use it on 1.12.2 now, I will use it in other versions later, thank you very much for your reply

**Comment by LoneDev6** [comment]
Thanks I appreciate your words

**Comment by Baikele** [comment]
> 谢谢我很欣赏你的话

[01:02:04] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ScratchIt v1.1.16
org.bukkit.event.EventException: null
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:274) [CraftEventFactory.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:241) [CraftEventFactory.class:git-CatServer-1.12.2-a8b73e9]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:237) [CraftEventFactory.class:git-CatServer-1.12.2-a8b73e9]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:1187) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) [mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) [mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_321]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_321]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:890) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 4, Size: 4)
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:369) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
        at dev.lone.ScratchIt.main.cw.d(SourceFile:103) ~[?:?]
        at dev.lone.ScratchIt.main.be.B(SourceFile:183) ~[?:?]
        at dev.lone.ScratchIt.main.be.<init>(SourceFile:95) ~[?:?]
        at dev.lone.ScratchIt.main.bg.<init>(SourceFile:98) ~[?:?]
        at dev.lone.ScratchIt.main.aB.a(SourceFile:241) ~[?:?]
        at dev.lone.ScratchIt.g.a(SourceFile:36) ~[?:?]
        at dev.lone.ScratchIt.a.a(SourceFile:204) ~[?:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-a8b73e9]
        ... 18 more

**Comment by LoneDev6** [comment]
Seems something to do with Cat server.
Please try normal Spigot or Paper, let me know.
