### ISSUE TITLE
[BUG] Large console Error using cards

### ISSUE THREAD

**Issue by L3v3lup** [PluginBugs/Issues-ScratchIt#6]
**Describe the bug**
This console error appears:
```
[01:38:04 ERROR]: Could not pass event PlayerInteractEvent to ScratchIt v1.1.14
java.lang.StringIndexOutOfBoundsException: begin 0, end -3, length 0
        at java.lang.String.checkBoundsBeginEnd(String.java:4601) ~[?:?]
        at java.lang.String.substring(String.java:2704) ~[?:?]
        at dev.lone.ScratchIt.main.bg.start(SourceFile:153) ~[ScratchIt.jar:?]
        at dev.lone.ScratchIt.a.a(SourceFile:204) ~[ScratchIt.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1598]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1983) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1598]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**To Reproduce**
- Just rightclick the card

**Info (please complete the following information):**
 - Server version: MC 1.18.2, Purpur-1598
 - Client version: MC 1.18.
 - Plugin version: 1.1.14

**Additional context**
This is happens even with default cards. (For exampel "Homework"

**Comment by L3v3lup** [comment]
Found the cause of the bug:
Disabling the cancel-settings in the config, makes it throw this error.
```
cards:
  usage_cooldown_ticks: 20
  cancel_scratching_methods:
    item_swap_F: false
    drop: false
    shift: false
```
It is **not** caused by a faulty config, this should not happen. Its since 1.1.14.

**Comment by LoneDev6** [comment]
Thanks! I will post an update today
